//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodestrikerPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodestrikerPlugin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codestriker Integration.
        /// </summary>
        public static string CodestrikerIntegration {
            get {
                return ResourceManager.GetString("CodestrikerIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codestriker URL.
        /// </summary>
        public static string CodestrikerUrl {
            get {
                return ResourceManager.GetString("CodestrikerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to Codestriker.
        /// </summary>
        public static string ConnectionFailure {
            get {
                return ResourceManager.GetString("ConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Topic.
        /// </summary>
        public static string CreateTopic {
            get {
                return ResourceManager.GetString("CreateTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error occured.
        /// </summary>
        public static string ErrorUnspecified {
            get {
                return ResourceManager.GetString("ErrorUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of Codestriker URL.
        /// </summary>
        public static string InvalidUrlFormat {
            get {
                return ResourceManager.GetString("InvalidUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing configuration data.
        /// </summary>
        public static string MissingConfigData {
            get {
                return ResourceManager.GetString("MissingConfigData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default browser configured.
        /// </summary>
        public static string NoDefaultBrowser {
            get {
                return ResourceManager.GetString("NoDefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find projects on the Server.
        /// </summary>
        public static string NoProjectsFound {
            get {
                return ResourceManager.GetString("NoProjectsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No shelveset selected.
        /// </summary>
        public static string NoShelvesetSelected {
            get {
                return ResourceManager.GetString("NoShelvesetSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send request.
        /// </summary>
        public static string SendFailure {
            get {
                return ResourceManager.GetString("SendFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timeout.
        /// </summary>
        public static string TimoutFailure {
            get {
                return ResourceManager.GetString("TimoutFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Description.
        /// </summary>
        public static string TopicDescription {
            get {
                return ResourceManager.GetString("TopicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No link to the topic could be found.
        /// </summary>
        public static string TopicLinkNotFound {
            get {
                return ResourceManager.GetString("TopicLinkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string TopicState {
            get {
                return ResourceManager.GetString("TopicState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Topic.
        /// </summary>
        public static string TopicTitle {
            get {
                return ResourceManager.GetString("TopicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not logged in!
        ///Please activate the Team Explorer Tool Window to authenticate against the connected TFS..
        /// </summary>
        public static string UserNotLoggedIn {
            get {
                return ResourceManager.GetString("UserNotLoggedIn", resourceCulture);
            }
        }
    }
}
